<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdFormaUnidadMedidaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'UNIDADES DE MEDIDA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'AGUJA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'AEROSOL','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'AMORTIZACION ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'AMPOLLA ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'ARROBA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BALDE ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BANDEJA ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BARRA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BARRIL (EEUU) 60 F','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BARRIL [42 GALONES(EEUU)]','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BARRILES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BIDON','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BLISTER','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BOBINAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BOLSA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BOLSA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BOTELLAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'BULTOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CAJA ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CAPSULA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CARTOLA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CARTONES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CARTUCHO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CENTIMETRO CUADRADO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CENTIMETRO CUBICO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CENTIMETRO LINEAL','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CIENTO DE UNIDADES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CILINDRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'COMPRIMIDO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CONJUNTO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'CONOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'DIAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'DISPLAY','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'DOCENA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'EQUIPOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'ESTUCHE','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'FANEGA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'FARDO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'FRASCO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'GALON INGLES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'GRAMO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'GRUESA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'HECTAREAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'HECTOLITRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'HOJA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'HORAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'JABA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'JERINGA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'JUEGO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'KILATES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'KILOGRAMO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'KILOMETRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'KILOVATIO HORA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'KILOWATT','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'KIT','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'LATAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'LIBRA FINA ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'LIBRAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'LITRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MEGAWATT','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MEGAWATT HORA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MESES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'METRO ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'METRO CUADRADO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'METRO CUBICO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'METRO CUBICO 60F VOL','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MIL PIES CUBICOS 14696 PSI','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MIL PIES CUBICOS 14696 PSI 68FAH','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILIGRAMOS ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILILITRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILIMETRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILIMETRO CUADRADO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILIMETRO CUBICO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILLAR DE PIES CUBICOS (1000PC)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILLARES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILLON DE UNIDADES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILLONES DE BTU (1000000BTU)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MILLONES DE PIES CUBICOS (1000000)PC','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'MINI BOTELLA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'ONZA TROY','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'ONZAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'OTRO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'OVULOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PACK','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PALETAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PAQUETE','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PAR','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PASTILLA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PIE TABLAR','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PIES ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PIES CUDRADOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PIES CUBICOS ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PIEZAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PIPETA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PLACAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PLIEGO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'POMO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'POTE','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'PULGADAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'QUINTAL','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'RESMA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'ROLLO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'SACHET','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'SOBRES','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'SUPOSITORIOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TABLETA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TAMBOR','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TERMO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TETRAPACK','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TIRA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TONELADA CORTA ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TONELADA LARGA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TONELADA METRICA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TONELADAS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TUBO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TUBOS','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'TURRIL','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'UNIDAD (BIENES)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'UNIDAD (SERVICIOS)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'UNIDAD TERMICA BRITANICA (TI)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'US GALON (3,7843 L)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'VASO','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'VIAL','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'YARDA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'YARDA','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'YARDA CUADRADA','activo'=>1]);
    }
}
